Flesh out dscription of SIGs and Units and create stub files for active units
unifoss/unifoss.github.io pull request #3
Opened 2021-06-20 14:26 UTC by MadhavJivrajani

- Add further descripion of what a Unit and what a SIG is and what their scopes are
- Add a way to create a Unit and a basic template for infomration needed by them.
    - Up for discussion
- Fixed a few links
- Create a stub file for active units

2021-06-20 15:48 UTC, MadhavJivrajani commented
Merge after #1 and #2, will need to fix merge conflicts

2021-06-21 12:35 UTC, tfidfwastaken requested changes
Thanks for the changes, this is pretty much on point, and improves the docs.

I am not sure about the Units for non-FOSS stuff. If you disagree, we'll try to reach some consensus on the group.

2021-06-21 12:35 UTC, tfidfwastaken commented on src/organisation-structure.md
> +A Unit can be any FOSS community, or a group of individuals with a specific goal or cause. It can be a FOSS project, or an existing college club or just a group of people sharing some interest: know
I am not sure if we should encourage Units for things that are not exactly FOSS, like baking. Maybe we can mention stuff like this in our "What to do" page, and suggest that we can make channels for such activities.

I always imagined Units to be something that is directly FOSS-related.

2021-06-21 12:35 UTC, tfidfwastaken commented on src/organisation-structure.md
> +A Unit is in no way subordinate to UniFOSS. They are completely autonomous and can be organised in any way they prefer, they can have their own logos, branding, etc. Do what's best for your Unit. The
I think [1] won't render correctly as footnotes. You'll need to do it like this [^1]

[^1] the actual footnote remains the same

2021-06-21 12:35 UTC, tfidfwastaken commented on src/organisation-structure.md
> +It's highy important that the goals of a SIG are well defined so as to prevent overlapping responsibilites between SIGs as much as possible.
highy -> highly

2021-06-21 12:35 UTC, tfidfwastaken commented on src/organisation-structure.md
> +- *Logistics*: Logistics could handle the organizational aspect of events, if a Unit wants to conduct an event, Logistics is the group that would help them out and provide necessary assistance.
This is a great example.

2021-06-21 12:35 UTC, tfidfwastaken commented on src/organisation-structure.md
> +2. If a Unit either grows in strength or scope such that the 'assets' (knowledge, ability to assist with issues of a specific nature, etc) of such a Unit can be beneficial to UniFOSS as a community a
Excellent addition.

2021-06-21 12:57 UTC, Samyak2 reviewed
Looks great! :+1:

2021-06-21 12:57 UTC, Samyak2 commented on src/guides/starting-a-unit.md
> +* A link to your GitHub/GitLab/etc organisation.
Adding to what Atharva said, it doesn't make sense to have an organization for non-FOSS related units.

2021-06-21 12:57 UTC, Samyak2 commented on src/organisation-structure.md
> +2. If a Unit either grows in strength or scope such that the 'assets' (knowledge, ability to assist with issues of a specific nature, etc) of such a Unit can be beneficial to UniFOSS as a community a
```suggestion
2. If a Unit either grows in strength or scope such that the 'assets' (knowledge, ability to assist with issues of a specific nature, etc) of such a Unit can be beneficial to UniFOSS as a community and not just the members of that Unit, then such a Unit would be *asked* if they would like to be 'graduated' to a SIG to help better serve the needs of the community, if the Unit is not comfortable doing so, that is *completely* okay as well.
```

2021-06-21 13:03 UTC, MadhavJivrajani commented
merges resolved and comments addressed
PTAL

2021-06-21 13:07 UTC, tfidfwastaken commented on src/organisation-structure.md
> +- A Unit of people who like to put on their tin foil hats and discuss conspiracy theories.
Was this left in by mistake?

2021-06-21 13:07 UTC, MadhavJivrajani commented
Oh wait 
Missed something

2021-06-21 13:07 UTC, MadhavJivrajani commented on src/organisation-structure.md
> +- A Unit of people who like to put on their tin foil hats and discuss conspiracy theories.
Yes XD

2021-06-21 13:07 UTC, MadhavJivrajani commented on src/organisation-structure.md
> +- A Unit of people who like to put on their tin foil hats and discuss conspiracy theories.
Lemme fix that

2021-06-21 13:08 UTC, Samyak2 reviewed
Some minor things

2021-06-21 13:08 UTC, Samyak2 commented on src/guides/starting-a-unit.md
> +We have made this easy for you. If you do not explicitly create or adopt your own Code of Conduct, our [Unit Code of Conduct](../unit-code-of-conduct.md) will apply to your Unit. You must have your C
It looks a little bad without the indentation here.

![image](https://user-images.githubusercontent.com/34161949/122766811-9082a680-d2bf-11eb-9273-f610d249efe1.png)

```suggestion
    We have made this easy for you. If you do not explicitly create or adopt your own Code of Conduct, our [Unit Code of Conduct](../unit-code-of-conduct.md) will apply to your Unit. You must have your Code of Conduct publicly accessible in your Unit's organisation page.
```

2021-06-21 13:08 UTC, Samyak2 commented on src/guides/starting-a-unit.md
> +This is to ensure that you can be contacted reliably, and also so that people have an outlet to report Code of Conduct violations.
and here.
```suggestion
    This is to ensure that you can be contacted reliably, and also so that people have an outlet to report Code of Conduct violations.
```

2021-06-21 13:09 UTC, tfidfwastaken commented
Also what's PTAL 🙃

2021-06-21 13:10 UTC, Samyak2 commented
> Also what's PTAL upside_down_face

I think that's "Please Take Another Look", not sure though

2021-06-21 13:10 UTC, MadhavJivrajani commented
Depending on context, 
- please take a look
- please take another look XD

2021-06-21 13:20 UTC, tfidfwastaken commented on src/organisation-structure.md
> +A Unit can be any FOSS community, or a group of individuals with a specific goal or cause. It can either be a FOSS project, or an existing college club. A Unit is in no way subordinate to UniFOSS. Th
One last change, I noticed this now. The line:
> A Unit is in no way subordinate to UniFOSS. They are completely autonomous and can be organised in any way they prefer. The only requirement for a Unit is they need to adopt a clear Code of Conduct[^1] that is reliably enforced.

Let's remove that from here, and keep it only under the heading below

is repeated here as well as below.

2021-06-21 13:22 UTC, MadhavJivrajani commented on src/organisation-structure.md
> +A Unit can be any FOSS community, or a group of individuals with a specific goal or cause. It can either be a FOSS project, or an existing college club. A Unit is in no way subordinate to UniFOSS. Th
Yep, check once after the merge conflict

2021-06-22 16:24 UTC, tfidfwastaken approved these changes

2021-06-22 16:25 UTC, merged